"""Add diagnoses table

Revision ID: 37b555524bee
Revises: 9580c6c1f660
Create Date: 2026-09-06 05:02:52.190206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37b555524bee'
down_revision: Union[str, Sequence[str], None] = '9580c6c1f660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnoses',
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('crop', sa.Enum('maize', 'tomato', 'potato', name='crop_type'), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('symptoms_text', sa.Text(), nullable=True),
    sa.Column('predicted_disease', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_referred', sa.Boolean(), nullable=False),
    sa.Column('officer_response', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('diagnosis_id')
    )
    op.create_index(op.f('ix_diagnoses_diagnosis_id'), 'diagnoses', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_user_id'), 'diagnoses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnoses_user_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_diagnosis_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    sa.Enum(name='crop_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
